repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-merge-conflict
  - id: debug-statements
  - id: name-tests-test
- repo: local
  # run all of these hooks from the Poetry versions
  hooks:
  - id: isort
    name: isort
    entry: python3 -m isort
    language: system
    types: [python]
    require_serial: true
  - id: black
    name: black
    entry: python3 -m black
    language: system
    types: [python]
    require_serial: true
  - id: flake8
    name: flake8
    entry: python3 -m flake8
    language: system
    types: [python]
    require_serial: true
