apiVersion: v1
kind: Service
metadata:
  name: ssh-balancer
  namespace: ros
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      name: ssh
      protocol: TCP
  selector:
    app: ssh-pod
